import type { SplitSectionKey } from "@/actions/propertyActions";
import { PROPERTY_SECTION_ORDER } from "@/types/jarvis-property-sections";

export const SPLIT_SECTION_ORDER: SplitSectionKey[] = [...PROPERTY_SECTION_ORDER];

export const SPLIT_SECTION_LABELS: Record<SplitSectionKey, string> = {
  DETAIL: "Detail",
  AUDIT_MANAGEMENT: "Audit & Management",
  ADDRESS: "Address",
  GOOGLE_PLACE: "Google Place",
  DAY_WISE_VARIABLES: "Day Wise Variables",
  SPECIAL_DATES: "Special Dates",
  AMENITIES_ACTIVITIES: "Amenities & Activities",
  GALLERY: "Gallery",
  SAFETY_HYGIENE: "Safety / Hygiene",
  SPACES: "Spaces",
  OWNERS: "Owners",
  MANAGERS: "Managers",
  CARETAKERS: "Caretakers",
  PLANS: "Plans",
  ICAL_INTEGRATION: "iCal Integration",
  BEDDING_AVAILABILITY: "Bedding Availability",
  ACTIVITIES_NEARBY_ATTRACTIONS: "Activities & Nearby Attractions",
  FOOD_OPTIONS: "Food Options",
  MISC_CHARGES: "Misc Charges",
  OTHERS: "Others",
};

export const SPLIT_SECTION_DESCRIPTIONS: Record<SplitSectionKey, string> = {
  DETAIL: "Core identity fields like property name, code, slug and code name.",
  AUDIT_MANAGEMENT: "Property audit management and checklist settings.",
  ADDRESS: "Address and geo fields used for location and discovery.",
  GOOGLE_PLACE: "Google place metadata, reviews and nearby places.",
  DAY_WISE_VARIABLES: "Daily pricing, discounts and base guest controls.",
  SPECIAL_DATES: "Date-specific price and guest charge overrides.",
  AMENITIES_ACTIVITIES: "Amenities and activities attached to the property.",
  GALLERY: "Gallery and cover images for property presentation.",
  SAFETY_HYGIENE: "Safety and hygiene checklist mapping.",
  SPACES: "Spaces and room-level descriptive information.",
  OWNERS: "Owners mapped to this property.",
  MANAGERS: "Managers mapped to this property.",
  CARETAKERS: "Caretakers mapped to this property.",
  PLANS: "Discount and cancellation plan assignments.",
  ICAL_INTEGRATION: "iCal import/export links and sync settings.",
  BEDDING_AVAILABILITY: "Bedding inventory and availability details.",
  ACTIVITIES_NEARBY_ATTRACTIONS: "Activities, attractions and nearby recommendations.",
  FOOD_OPTIONS: "Food availability and meal option details.",
  MISC_CHARGES: "Additional charges and fee configuration.",
  OTHERS: "Description, policy, FAQ and metadata fields.",
};

export const SPLIT_SECTION_RECOMMENDATION: Record<SplitSectionKey, "Usually inherit" | "Usually customize"> = {
  DETAIL: "Usually customize",
  AUDIT_MANAGEMENT: "Usually inherit",
  ADDRESS: "Usually inherit",
  GOOGLE_PLACE: "Usually inherit",
  DAY_WISE_VARIABLES: "Usually customize",
  SPECIAL_DATES: "Usually customize",
  AMENITIES_ACTIVITIES: "Usually inherit",
  GALLERY: "Usually inherit",
  SAFETY_HYGIENE: "Usually inherit",
  SPACES: "Usually inherit",
  OWNERS: "Usually inherit",
  MANAGERS: "Usually inherit",
  CARETAKERS: "Usually inherit",
  PLANS: "Usually inherit",
  ICAL_INTEGRATION: "Usually inherit",
  BEDDING_AVAILABILITY: "Usually inherit",
  ACTIVITIES_NEARBY_ATTRACTIONS: "Usually inherit",
  FOOD_OPTIONS: "Usually inherit",
  MISC_CHARGES: "Usually inherit",
  OTHERS: "Usually customize",
};

export const SPLIT_PRESET_MODES: Record<
  "MOSTLY_INHERIT" | "PRICING_ONLY_CUSTOM" | "MARKETING_VARIANT",
  Record<SplitSectionKey, "INHERIT" | "CUSTOM">
> = {
  MOSTLY_INHERIT: {
    DETAIL: "CUSTOM",
    AUDIT_MANAGEMENT: "INHERIT",
    ADDRESS: "INHERIT",
    GOOGLE_PLACE: "INHERIT",
    DAY_WISE_VARIABLES: "INHERIT",
    SPECIAL_DATES: "INHERIT",
    AMENITIES_ACTIVITIES: "INHERIT",
    GALLERY: "INHERIT",
    SAFETY_HYGIENE: "INHERIT",
    SPACES: "INHERIT",
    OWNERS: "INHERIT",
    MANAGERS: "INHERIT",
    CARETAKERS: "INHERIT",
    PLANS: "INHERIT",
    ICAL_INTEGRATION: "INHERIT",
    BEDDING_AVAILABILITY: "INHERIT",
    ACTIVITIES_NEARBY_ATTRACTIONS: "INHERIT",
    FOOD_OPTIONS: "INHERIT",
    MISC_CHARGES: "INHERIT",
    OTHERS: "INHERIT",
  },
  PRICING_ONLY_CUSTOM: {
    DETAIL: "CUSTOM",
    AUDIT_MANAGEMENT: "INHERIT",
    ADDRESS: "INHERIT",
    GOOGLE_PLACE: "INHERIT",
    DAY_WISE_VARIABLES: "CUSTOM",
    SPECIAL_DATES: "CUSTOM",
    AMENITIES_ACTIVITIES: "INHERIT",
    GALLERY: "INHERIT",
    SAFETY_HYGIENE: "INHERIT",
    SPACES: "INHERIT",
    OWNERS: "INHERIT",
    MANAGERS: "INHERIT",
    CARETAKERS: "INHERIT",
    PLANS: "INHERIT",
    ICAL_INTEGRATION: "INHERIT",
    BEDDING_AVAILABILITY: "INHERIT",
    ACTIVITIES_NEARBY_ATTRACTIONS: "INHERIT",
    FOOD_OPTIONS: "INHERIT",
    MISC_CHARGES: "CUSTOM",
    OTHERS: "INHERIT",
  },
  MARKETING_VARIANT: {
    DETAIL: "CUSTOM",
    AUDIT_MANAGEMENT: "INHERIT",
    ADDRESS: "INHERIT",
    GOOGLE_PLACE: "CUSTOM",
    DAY_WISE_VARIABLES: "INHERIT",
    SPECIAL_DATES: "INHERIT",
    AMENITIES_ACTIVITIES: "CUSTOM",
    GALLERY: "INHERIT",
    SAFETY_HYGIENE: "INHERIT",
    SPACES: "CUSTOM",
    OWNERS: "INHERIT",
    MANAGERS: "INHERIT",
    CARETAKERS: "INHERIT",
    PLANS: "INHERIT",
    ICAL_INTEGRATION: "INHERIT",
    BEDDING_AVAILABILITY: "INHERIT",
    ACTIVITIES_NEARBY_ATTRACTIONS: "CUSTOM",
    FOOD_OPTIONS: "CUSTOM",
    MISC_CHARGES: "INHERIT",
    OTHERS: "CUSTOM",
  },
};

