export const PROPERTY_SECTION_KEYS = [
  "DETAIL",
  "AUDIT_MANAGEMENT",
  "ADDRESS",
  "GOOGLE_PLACE",
  "DAY_WISE_VARIABLES",
  "SPECIAL_DATES",
  "AMENITIES_ACTIVITIES",
  "BEDDING_AVAILABILITY",
  "ACTIVITIES_NEARBY_ATTRACTIONS",
  "FOOD_OPTIONS",
  "MISC_CHARGES",
  "GALLERY",
  "SAFETY_HYGIENE",
  "SPACES",
  "OWNERS",
  "MANAGERS",
  "CARETAKERS",
  "PLANS",
  "ICAL_INTEGRATION",
  "OTHERS",
] as const;

export type PropertySectionKey = (typeof PROPERTY_SECTION_KEYS)[number];

export const PROPERTY_SECTION_ORDER = PROPERTY_SECTION_KEYS;
